### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by sometheasiekswx**
To prevent accidentally committing unwanted code.

### CODE REVIEW

**Comment by aidanjgriffiths** [comment]
It seems a bit excessive to add all these exceptions when we are likely not going to use them, could we maybe extract the python specific stuff we want to exclude and get rid of the rest?

**Comment by aidanjgriffiths** [comment]
@sometheasiekswx have a look at [this gist](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c) as I mostly agree with the points made. I think this is more of a developer tool to set globally rather than commit to a repository. 

I think you should have a look at what python files can be generated as a side effect of running the tool (`*.db`, `htmlcov/`, `*.pyc`, `__pycache__`, ect) to produce a more curated version of this file. We can then roll out more filetypes as we need them.

**Review by aidanjgriffiths — COMMENTED** [review]
See above comments as review feedback.

**Comment by sometheasiekswx** [comment]
@aidanjgriffiths I've modified PR, can you check it again?

**Comment by sometheasiekswx** [comment]
> @sometheasiekswx have a look at [this gist](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c) as I mostly agree with the points made. I think this is more of a developer tool to set globally rather than commit to a repository.
> 
> I think you should have a look at what python files can be generated as a side effect of running the tool (`*.db`, `htmlcov/`, `*.pyc`, `__pycache__`, ect) to produce a more curated version of this file. We can then roll out more filetypes as we need them.

After reading the gist, I do agree with it. In a perfect world, every dev has a global .gitignore setup, but that's not the case. Having editors/os in .gitignore added an extra layer of security to prevent a dev from accidentally committing their vscode configs.

**Comment by aidanjgriffiths** [comment]
Ok @sometheasiekswx feel free to merge I'll move your Trello ticket to the completed section.

**Pull request merged**
