### PR TITLE
Allow database creation within enrollment workflow

### PR DESCRIPTION
**Pull request by aidanjgriffiths**
A quickfix branch that restore the sqlite database implementation for saving user enrolments.

### CODE REVIEW

**Review by nnfunny — COMMENTED** [review]
- Changes in `__init__.py` and `__main__.py` are clear and appropriate to have better abstract arguments and add more functionality for accepting the selected database table via command line.
- In `sql_utils.py`, the functional approach that you designed for SQL functionalities is concise and prevents side effects. However, I can see we can use OOP to create a SQL utils object in order to connect to the database only one time in the constructor instead of repeating it multiple times as executing any operation related to the database. What do you think about my idea?

**Comment by aidanjgriffiths** [comment]
>     * n
I think that's a great idea @nnfunny, did you want to create a new issue for refactoring the `sql_utils.py` and take ownership of making the changes?

**Comment by nnfunny** [comment]
I got your counter-argument via the article you shared above. The functional approach and constant variables used in `sql_utils` are consistent and preventing from introducing bugs and side effects. I think we can keep your method since we can change `DATABASE_PATH` in just one place, and we also connect the DB as needed instead of instantiating an object in memory and using it once.

**Comment by nnfunny** [comment]
> > ```
> > we can use OOP to create a SQL utils object in order to connect to the database only one time
> > ```
> 
> I think that's a great idea @nnfunny, did you want to create a new issue for refactoring the `sql_utils.py` and take ownership of making the changes?
> 
> EDIT: I might add that [this is a good counter argument](https://sandimetz.com/blog/2016/1/20/the-wrong-abstraction) to your OOP suggestion given the current context in which the package is executed. However I believe that the proposed changes are necessary and actually make `sql_utils.py` more simple, testable and maintainable for the future.

**Comment by nnfunny** [comment]
> > ```
> > we can use OOP to create a SQL utils object in order to connect to the database only one time
> > ```
> 
> I think that's a great idea @nnfunny, did you want to create a new issue for refactoring the `sql_utils.py` and take ownership of making the changes?
> 
> EDIT: I might add that [this is a good counter argument](https://sandimetz.com/blog/2016/1/20/the-wrong-abstraction) to your OOP suggestion given the current context in which the package is executed. However I believe that the proposed changes are necessary and actually make `sql_utils.py` more simple, testable and maintainable for the future.

**Pull request merged**
